### ISSUE TITLE
What does LMScore mean?

### ISSUE THREAD

**Issue by zxch3n** [Microsoft/DualLearning#2]
It's used often in this project, even in the loss. But I cannot find any documentation about this value. 

https://github.com/Microsoft/DualLearning/blob/1068687f839bb05b01c69833b2852cdbf488a2c2/DSL_ImgProcess/data2/cifar10_data.py#L80-L85

https://github.com/Microsoft/DualLearning/blob/6c7873747400359bd0f0aa69dabe23b814ea2f0f/DSL_ImgProcess/monitor.py#L399-L400

https://github.com/Microsoft/DualLearning/blob/6c7873747400359bd0f0aa69dabe23b814ea2f0f/DSL_ImgProcess/monitor.py#L152-L157

Does it mean the probability of the image?

**Comment by alphadl** [comment]
For NLP tasks, LM score regularly refers to the [language model](https://en.wikipedia.org/wiki/Language_model) score (metric is [perplexity](https://en.wikipedia.org/wiki/Perplexity)) to represent the sentence probability @rem2016

**Comment by zxch3n** [comment]
Thanks!
